
server:
  port: 3000

database:
  connection: ""

error:
  message: "We are facing some technical problems, please try again later..."

api:
  url : "https://test-api.lescapes.com/api/public-offers"
  active_only: false
  cache_time: 1800   # in sec
  status:
    success: 200
